spring.application.name=Digital_warranty

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/Digital_warranty
spring.datasource.username=root
spring.datasource.password=34tyuiuygv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=rtyghjkljhgvcvbhjkl
jwt.expiration=456789

# ===============================
# CLOUDINARY CONFIGURATION
# ===============================
cloudinary.cloud-name=47475745
cloudinary.api-key=9689678iy6
cloudinary.api-secret=erfghnmkiuygcxdgh

# ===============================
# EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thejadg2006@gmail.com
spring.mail.password=rdftgyuhijhgvcvb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FILE UPLOAD CONFIGURATION
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB