spring.application.name=Digital_warranty

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/Digital_warranty
spring.datasource.username=root
spring.datasource.password=Sneha@220
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=ThisIsAVerySecretKeyForDigitalWarrantyTrackerProject2026
jwt.expiration=86400000

# ===============================
# CLOUDINARY CONFIGURATION
# ===============================
cloudinary.cloud-name=ufsojlp2
cloudinary.api-key=414222386317173
cloudinary.api-secret=xNPxpJg_reHbflhJpSSHN4NtorM

# ===============================
# EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thejasreek2006@gmail.com
spring.mail.password=zebjhnwcmqcjsssu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FILE UPLOAD CONFIGURATION
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB