spring.application.name=Digital_warranty

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/dfghj
spring.datasource.username=root
spring.datasource.password=4567890iuy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=Tjhgfghjk
jwt.expiration=987654

# ===============================
# CLOUDINARY CONFIGURATION
# ===============================
cloudinary.cloud-name=sdfghjk
cloudinary.api-key=78945678973
cloudinary.api-secret=4rtgfbjhgcx

# ===============================
# EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=34567uijhb
spring.mail.password=dfghjk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FILE UPLOAD CONFIGURATION
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB